language: php
php:
#  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install
  - mysql -e 'create database jaludo;'
  - ./propel-gen
  - ./propel-gen insert-sql


script: phpunit --configuration phpunit.xml --coverage-text

branches:
  only:
    - master
